[project]
name = "Backend-PortalDeOportunidaes"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "renato-cm", email = "renatochagas.m@gmail.com"},
]
dependencies = ["django>=5.2.6", "djangorestframework>=3.16.1"]
requires-python = ">=3.13"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pdm.scripts]
dev = "python src/manage.py runserver"
createsuperuser = "python src/manage.py createsuperuser"
pre_migrate = "python src/manage.py makemigrations"
migrate = "python src/manage.py migrate"
shell = "python src/manage.py shell"
test = "python src/manage.py test"
