# Generated by Django 5.2.6 on 2025-09-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalDeOportunidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('area', models.CharField(max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='Exemplo',
        ),
    ]
