# Generated by Django 5.2.6 on 2025-09-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalDeOportunidades', '0002_curso_delete_exemplo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('palestrante', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
