# Generated by Django 5.2.6 on 2025-09-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalDeOportunidades', '0003_evento_alter_curso_area_alter_curso_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150)),
                ('numero_edital', models.CharField(max_length=50)),
                ('data_publicacao', models.DateField()),
                ('data_validade', models.DateField()),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
            },
        ),
    ]
