# Generated by Django 5.2.6 on 2025-09-27 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalDeOportunidades', '0004_edital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('local', models.CharField(max_length=300)),
                ('carga_horaria', models.CharField(max_length=80)),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='area',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='edital',
            name='descricao',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='evento',
            name='palestrante',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PortalDeOportunidades.edital')),
                ('estagio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PortalDeOportunidades.estagio')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PortalDeOportunidades.evento')),
            ],
        ),
    ]
