# Generated by Django 5.2.6 on 2025-10-05 16:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalDeOportunidades', '0005_estagio_alter_curso_area_alter_curso_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(default='IFC', max_length=200),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
